
package com.aspire.service.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.aspire.service.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MyService", targetNamespace = "http://service.aspire.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MyService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://service.aspire.com/", className = "com.aspire.service.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://service.aspire.com/", className = "com.aspire.service.AddResponse")
    @Action(input = "http://service.aspire.com/MyService/addRequest", output = "http://service.aspire.com/MyService/addResponse")
    public int add(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "minus", targetNamespace = "http://service.aspire.com/", className = "com.aspire.service.Minus")
    @ResponseWrapper(localName = "minusResponse", targetNamespace = "http://service.aspire.com/", className = "com.aspire.service.MinusResponse")
    @Action(input = "http://service.aspire.com/MyService/minusRequest", output = "http://service.aspire.com/MyService/minusResponse")
    public int minus(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
